spring:
  application:
    name: strhat

  datasource:
    url: ${MYSQL_HOST}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

swagger:
  server:
    url: ${SWAGGER_URL}

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC  # path, query, body, response ? ??
    tags-sorter: alpha  # ?? ??? ? ??
    operations-sorter: default
    persist-authorization: true
    display-request-duration: true

openai:
  api:
    key: ${OPENAI_API_KEY}
    model: gpt-4o
#    model: gpt-3.5-turbo
    organization: ${OPENAI_ORGANIZATION}
    project: ${OPENAI_PROJECT_ID}
    temperature: 0.7
    max-tokens: 500
